// layout.metadata.tsx

import type { Metadata } from "next";

// Định nghĩa metadata ngoài component (không có "use client")
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
